### PR TITLE
Set execute permission

### PR DESCRIPTION
**Pull request by nemchik**
For those of us (probably just me) who `git pull` your repo and run the script from there (rather than the suggested `wget` in the readme) this permission change would be much appreciated.

### CODE REVIEW

**Comment by Unimatrix0** [comment]
I have no strong objection to this, but do you really want to download a file and have it immediately executable?

**Comment by nemchik** [comment]
Honestly I would rather git ignore the permissions on the file, thus during an initial download it would not be executable, but if I set the permissions myself git should not complain about changes in the repo. Unfortunately I do not know how to do that, so this was my next best idea. If there's a better way I'm all for it.

**Comment by Unimatrix0** [comment]
@nemchik try `git config core.fileMode false`

**Comment by nemchik** [comment]
Will that affect all git repos i have cloned or just this one if i run it in the directory for this repo?

**Comment by Unimatrix0** [comment]
Should be per-repo.

There's a global setting also, but the command I suggested shouldn't affect it.

Let me know if that resolves this issue.

**Comment by nemchik** [comment]
Yes, that command does seem to solve the issue.

**Pull request closed without merging**
