### PR TITLE
Add config argument

### PR DESCRIPTION
**Pull request by ghost**
Add config to arguments using --config= or -c=, also quotes can be used for paths with spaces.
If config argument is not used it will check for config in the same folder as before.
Add config path to log level debug.

### CODE REVIEW

**Review by didyouexpectthat — COMMENTED** [review]
Something didn't seem to work here for me. 
If I use the `-c=/path/to/file` option, it works, but the `--config` did not.
```
# /opt/update_ombi/update_ombi2.sh
p/tmp.yTWgGSdpWp/ombi_3.0.268  55%[==========================>                      ]  25.04M  39.5MB/s
[CTRL+C]
# /opt/update_ombi/update_ombi2.sh -c=/opt/update_ombi/update_ombi2.conf
[17:30:18] [info] Script config file found...parsing...
[17:30:18] [debug] Config path is: /opt/update_ombi/update_ombi2.conf
[17:30:18] [info] Parsed config file
[17:30:18] [info] update_ombi v1.1.02
[17:30:18] [info] Verbosity level: [debug]
[17:30:18] [debug] Update script running as: root
[17:30:18] [notice] InstallDir not parsed...setting to default: /opt/ombi
[17:30:18] [notice] User not parsed...setting to default: ombi
[17:30:18] [notice] Group not parsed...setting to default: ombi
[17:30:18] [notice] IP not parsed or set as "*"...setting to default: 127.0.0.1
[17:30:18] [notice] Port not parsed...setting to default: 5001
[17:30:18] [info] Downloading Ombi update...
[17:30:18] [info] Checking for latest version
[17:30:19] [debug] latestversion: 3.0.2689
[17:30:19] [debug] jobId: 54kqh2ixun6v55vq
[17:30:19] [debug] version: 3.0.2689
[17:30:19] [info] Latest version: 3.0.2689...determining expected file size...
[17:30:19] [debug] size: 47261493
[17:30:19] [info] Expected file size: 47261493...downloading...
[CTRL+C]
# /opt/update_ombi/update_ombi2.sh --config /opt/update_ombi/update_ombi2.conf
******************************
* Error: Invalid config path.*
******************************
# /opt/update_ombi/update_ombi2.sh --config=/opt/update_ombi/update_ombi2.conf
****************************
* Error: Invalid argument. *
****************************
```

**Review by didyouexpectthat — CHANGES_REQUESTED** [review]
The problem exists with `--verbosity` as well.

This seemed to work for me and doesn't require the equal sign in `--config` but I am not sure if @Unimatrix0 is expecting there to be an = sign or not for `--options` so I defer to Avi.
```
    --config|-c=*)
    if [[ ${1#*=} =~ ^\"?.*\.conf\"?$ ]]; then
          configfile="${1#*=}"
    elif [[ ${2#*=} =~ ^\"?.*\.conf\"?$ ]]; then
          shift
          configfile="${1#*=}"
    else
          printf "******************************\n"
          printf "* Error: Invalid config path.*\n"
          printf "******************************\n"
          exit 1
      fi
      ;;
```

And some verbose output
```
# bash -x /opt/update_ombi/update_ombi2.sh --config /opt/update_ombi/update_ombi.conf
+ ombiservicename=ombi
+ logfile=/var/log/ombiupdater.log
+ ombiservicefile=/etc/systemd/system/ombi.service
+ defaultinstalldir=/opt/Ombi
+ defaultuser=ombi
+ defaultgroup=nogroup
+ defaultip=127.0.0.1
+ defaultport=5000
+ declare -i verbosity=-1
+ name=update_ombi
+ version=1.1.02
+ SECONDS=0
+ '[' 2 -gt 0 ']'
+ case "$1" in
+ [[ --config =~ ^"?.*\.conf"?$ ]]
+ [[ /opt/update_ombi/update_ombi.conf =~ ^"?.*\.conf"?$ ]]
+ shift
+ configfile=/opt/update_ombi/update_ombi.conf
+ shift
+ '[' 0 -gt 0 ']'
+ LOG_LEVELS=([-1]="none" [0]="emerg" [1]="alert" [2]="crit" [3]="err" [4]="warning" [5]="notice" [6]="info" [7]="debug" [8]="trace")
+ declare -A LOG_LEVELS
```

**Comment by nemchik** [comment]
I found the reason for the issue @didyouexpectthat is having. There's a missing `shift`. You can see my PR https://github.com/Unimatrix0/update_ombi/pull/24 where I have resolved the issue. The same could be done here and that would resolve the issue. (You would want to add a `shift` after `--config|-c=*)` and after `--verbosity|-v=*)` and that should fix it)

**Comment by Unimatrix0** [comment]
@didyouexpectthat [wrote](https://github.com/Unimatrix0/update_ombi/pull/18#pullrequestreview-89653614):
> This seemed to work for me and doesn't require the equal sign in --config but I am not sure if @Unimatrix0 is expecting there to be an = sign or not for --options so I defer to Avi.

Usage should be `--verbosity #` or `-v=#`.
It's expected behavior that --verbosity=# wouldn't work.

Re: --config, yes, the code should be `--config|-c=*)`

**Review by Unimatrix0 — CHANGES_REQUESTED** [review]
Add shifts as explained [here](https://github.com/Unimatrix0/update_ombi/pull/18#issuecomment-370865872)

**Comment by Unimatrix0** [comment]
It's been over a year, the requested changes have not been made. Closing.

**Pull request closed without merging**
