### PR TITLE
Switch from azure to local api for update checks

### LINKED ISSUE #19: 403 error
Looks like 'curl -sL https://ombiservice.azurewebsites.net/api/update/DotNetCore' is returning a 403 error

### PR DESCRIPTION
**Pull request by nemchik**
This resolves #19

### CODE REVIEW

**Comment by nemchik** [comment]
FYI @tidusjar renamed the `DotNetCore` branch to `develop` sometime over the weekend. I've added a second commit to this PR to compensate.

**Comment by nemchik** [comment]
I've found that this link should fetch the latest successful build at any given time:
https://ci.appveyor.com/api/projects/tidusjar/requestplex/artifacts/linux.tar.gz

According to https://github.com/appveyor/ci/issues/403

Maybe this could be beneficial in changing the script to just grab that url instead of doing the version comparing that it's doing? I'm not sure yet.

**Comment by tidusjar** [comment]
I wouldn't recommend that since it will grab any branch

**Comment by nemchik** [comment]
Good point. I didn't really consider other branches being in the mix. The issue also mentioned we could use https://ci.appveyor.com/api/projects/tidusjar/requestplex/artifacts/linux.tar.gz?branch=develop

**Comment by Unimatrix0** [comment]
This needs to account for which branch is currently running, ideally with the ability to override via config file.

Also, what happens if Ombi isn't running?

**Comment by nemchik** [comment]
I am not sure how to tell the currently running branch, but I'll look into it. It might not be possible without an authenticated request to the API (see https://github.com/Unimatrix0/update_ombi/pull/21)

If Ombi isn't running then the script would not work. Unfortunately the API capabilities of appveyor do not have a way to return the version of the most recently successful build. You can return a history of recent builds and then iterate through them to find a successful build, but you must specify the number of builds to return. In a scenario where the past X builds have failed, this script would need to iterate through at least X+1 builds without knowing the value of X. The script COULD make multiple calls to the API and increase X by 1 each time until it finds a successful build, but that would increase the time it takes to run and seems like a bad idea to repeatedly call the appveyor API over and over until you find a successful build (but that might just be me feeling bad).

**Comment by tidusjar** [comment]
If ombi isn't running couldn't you just output a message for the user?

**Comment by nemchik** [comment]
That's a possibility. I think in conjunction with https://github.com/Unimatrix0/update_ombi/pull/24 we could bypass the check if ombi is running and install the version specified no matter what.

**Comment by Unimatrix0** [comment]
@nemchik from appveyor support:

> Is this https://www.appveyor.com/docs/packaging-artifacts/#permalink-to-the-last-successful-build-artifact good enough for you?
> 
> If you need to get last successful build you need to iterate the build history. Here is the sample: https://gist.github.com/IlyaFinkelshteyn/63684c78d14164cb501ff496dc68e43b

**Comment by nemchik** [comment]
Yup, I've read. I've mentioned a few times that we need to iterate. The issue is parsing json without jq.

**Comment by schmittyd** [comment]
> Unfortunately the API capabilities of appveyor do not have a way to return the version of the most recently successful build

Yes, there is. If you do not specify the branch, it will return the most recently successful build.

**Comment by schmittyd** [comment]
> URL parameters:

branch - if not specified the most recent successful build of any branch is fetched.
tag - if not specified the most recent successful build of any tag is fetched.
job - the name of the job. If a build contains multiple jobs then this parameter is mandatory. Value must be URL-encoded, for example Configuration%3DRelease.
all - lookup for artifact in not only successful builds, but in successful, failed and cancelled ones. Default is false.
pr - include PR builds in the search results. true - take artifact from PR builds only, false - do not look for artifact in PR builds; otherwise look for artifact in both PR an non-PR builds.

**Comment by nemchik** [comment]
@schmittyd this script currently only deals with the beta builds from the develop branch. If we specify the branch then it returns the most recent build regardless of success.

**Comment by schmittyd** [comment]
the url doesn't seem to work when initiating from a bash script

**Pull request merged**
